version: '3'
services:

  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
     - 4000:4000
    depends_on:
      - db

  db:
    image: postgres:10.15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
